sudo: required
services:
  - docker

before_install:
  - docker build -t mross04/scratch-app -f Dockerfile.dev .

script:
  - docker run -e CI=true mross04/scratch-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "scratch-app"
  env: "ScratchApp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-804184065314"
  bucket_path: "scratch-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
